import type { Match, Person, QuestionField } from './types';
import type { SheetProfile } from './sheets';

const mkField = (
  key: string,
  question: string,
  answer: string,
  multi = false,
  section: 'about' | 'looking' = 'about',
): QuestionField => ({
  key,
  question,
  answer,
  values: answer
    .split(',')
    .map((v) => v.trim())
    .filter(Boolean),
  multi,
  section,
});

interface RawPersonInput {
  id: string;
  full_name: string;
  email: string;
  gender: 'male' | 'female';
  age: number;
  location: string;
  occupation: string;
  adminNote: string;
  bioDataUrl: string;
  about: Record<string, string>;
  looking: Record<string, string>;
}

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

const isMulti = (header: string): boolean =>
  /select all that apply/i.test(header);

function parseAbout(raw: Record<string, string>): QuestionField[] {
  return Object.entries(raw).map(([question, answer]) =>
    mkField(slug(question), question, answer, isMulti(question), 'about'),
  );
}

function parseLooking(raw: Record<string, string>): QuestionField[] {
  return Object.entries(raw).map(([question, answer]) =>
    mkField(slug(question), question, answer, isMulti(question), 'looking'),
  );
}

function buildPerson(input: RawPersonInput): Person {
  return {
    id: input.id,
    full_name: input.full_name,
    email: input.email,
    gender: input.gender,
    is_deleted: false,
    created_at: new Date('2025-01-10T10:00:00Z').toISOString(),
    updated_at: new Date('2025-01-10T10:00:00Z').toISOString(),
  };
}

function buildSheetProfile(input: RawPersonInput): SheetProfile {
  const about_you: Record<string, QuestionField> = {};
  const looking_for: Record<string, QuestionField> = {};
  parseAbout(input.about).forEach((f) => (about_you[f.key] = f));
  parseLooking(input.looking).forEach((f) => (looking_for[f.key] = f));
  return {
    email: input.email,
    full_name: input.full_name,
    gender: input.gender,
    age: input.age,
    location: input.location,
    occupation: input.occupation,
    profile_photo_url: null,
    photo_urls: [],
    admin_note: input.adminNote || null,
    bio_data_url: input.bioDataUrl || null,
    about_you,
    looking_for,
  };
}

const peopleRaw: RawPersonInput[] = [
  {
    id: 'm1',
    full_name: 'Aarav Khan',
    email: 'aarav.khan@example.com',
    gender: 'male',
    age: 28,
    location: 'Toronto, ON',
    occupation: 'Software Engineer',
    adminNote: 'Looking for someone active in the Toronto community.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpAaravKhanBioData/viewform',
    about: {
      'Birth Date': '1997-05-15',
      'Height': "5'10\"",
      'State You Reside In': 'Ontario',
      'Willingness to Relocate': 'Yes',
      'Country of Ethnicity': 'Pakistan',
      'Secondary Country of Ethnicity': 'India',
      'Past Marital Status': 'I was never married and have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I always plan to work full-time',
      'Prayer Habits': 'I pray 5 times a day',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic events/classes and listen to lectures sometimes',
      'Halal Food Preference': 'I require a Halal label or need to be told it is Halal',
      'Islamic Affiliation': 'Hanafi',
      'Hijab Status': 'N/A',
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'We both equally share housework and financial responsibilities',
      'Hobbies / Interests': 'Reading, Hiking, Board games',
    },
    looking: {
      "How Many Years Younger": '5',
      "How Many Years Older": '5',
      "Partner's Height Range (Shortest)": "5'2\"",
      "Partner's Height Range (Tallest)": "5'8\"",
      "Partner's State": 'Ontario',
      'Country of Ethnicity Preference': 'I am okay with her being any country of ethnicity but prefer my own',
      "Partner's Past Marital Status": 'She was never married and has no kids',
      "Partner's Employment Status": 'Working full-time',
      "Partner's Post-Marriage Employment": 'She always plans to work full-time',
      "Partner's Prayer Habits": 'He prays 5 times a day',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'She requires a Halal label or needs to be told it is Halal',
      "Partner's Islamic Affiliation": 'Hanafi',
      "Partner's Hijab Status": 'She wears a hijab',
      "Partner's Hobbies / Interests": 'Reading, Hiking',
    },
  },
  {
    id: 'm2',
    full_name: 'Bilal Rahman',
    email: 'bilal.rahman@example.com',
    gender: 'male',
    age: 32,
    location: 'Mississauga, ON',
    occupation: 'Pharmacist',
    adminNote: 'Prefer someone from a Bangladeshi background.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpBilalRahmanBioData/viewform',
    about: {
      'Birth Date': '1993-08-20',
      'Height': "5'11\"",
      'State You Reside In': 'Ontario',
      'Willingness to Relocate': 'No',
      'Country of Ethnicity': 'Bangladesh',
      'Secondary Country of Ethnicity': '',
      'Past Marital Status': 'I was never married and have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I always plan to work full-time',
      'Prayer Habits': 'I pray 5 times a day',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic events/classes and listen to lectures sometimes',
      'Halal Food Preference': 'I require a Halal label or need to be told it is Halal',
      'Islamic Affiliation': 'Hanafi',
      'Hijab Status': 'N/A',
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'Husband provides all finances and Wife will take care of home',
      'Hobbies / Interests': 'Cricket, Volunteering, Travel',
    },
    looking: {
      "How Many Years Younger": '5',
      "How Many Years Older": '5',
      "Partner's Height Range (Shortest)": "5'3\"",
      "Partner's Height Range (Tallest)": "5'9\"",
      "Partner's State": 'Ontario',
      'Country of Ethnicity Preference': 'She must be from my country of ethnicity',
      "Partner's Past Marital Status": 'She was never married and has no kids',
      "Partner's Employment Status": 'Working full-time',
      "Partner's Post-Marriage Employment": 'She always plans to work full-time',
      "Partner's Prayer Habits": 'He prays 5 times a day',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'She requires a Halal label or needs to be told it is Halal',
      "Partner's Islamic Affiliation": 'Hanafi',
      "Partner's Hijab Status": 'She wears a hijab',
      "Partner's Hobbies / Interests": 'Travel, Volunteering',
    },
  },
  {
    id: 'm3',
    full_name: 'Yusuf Ahmed',
    email: 'yusuf.ahmed@example.com',
    gender: 'male',
    age: 30,
    location: 'Calgary, AB',
    occupation: 'Civil Engineer',
    adminNote: 'Open to relocating within Canada.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpYusufAhmedBioData/viewform',
    about: {
      'Birth Date': '1995-03-10',
      'Height': "5'9\"",
      'State You Reside In': 'Alberta',
      'Willingness to Relocate': 'Yes',
      'Country of Ethnicity': 'Egypt',
      'Secondary Country of Ethnicity': 'Palestine',
      'Past Marital Status': 'I was never married and have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I always plan to work full-time',
      'Prayer Habits': 'I am trying my best to pray 5 times daily but occasionally miss',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic classes a once or few times a week',
      'Halal Food Preference': 'I need to at least be told that the meat is hand-slaughtered',
      'Islamic Affiliation': 'Shafi',
      'Hijab Status': 'N/A',
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'We both equally share housework and financial responsibilities',
      'Hobbies / Interests': 'Soccer, Photography, Cooking',
    },
    looking: {
      "How Many Years Younger": '5',
      "How Many Years Older": '5',
      "Partner's Height Range (Shortest)": "5'2\"",
      "Partner's Height Range (Tallest)": "5'7\"",
      "Partner's State": 'Alberta, Ontario',
      'Country of Ethnicity Preference': 'I am okay with any country of ethnicity',
      "Partner's Past Marital Status": 'She was never married and has no kids',
      "Partner's Employment Status": 'Working full-time, Working part-time',
      "Partner's Post-Marriage Employment": 'She always plans to work full-time, She plans to work until kids and then will stop working',
      "Partner's Prayer Habits": 'He prays 5 times a day, He is trying his best to pray 5 times daily but occasionally misses',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic classes a once or few times a week, He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'She needs to at least be told that the meat is hand-slaughtered',
      "Partner's Islamic Affiliation": 'Shafi, Hanafi',
      "Partner's Hijab Status": 'She wears a hijab, She doesn\'t wear a hijab but is working towards it',
      "Partner's Hobbies / Interests": 'Soccer, Cooking, Photography',
    },
  },
  {
    id: 'm4',
    full_name: 'Imran Sheikh',
    email: 'imran.sheikh@example.com',
    gender: 'male',
    age: 35,
    location: 'Vancouver, BC',
    occupation: 'Financial Analyst',
    adminNote: 'Divorced, no children. Serious inquiries only.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpImranSheikhBioData/viewform',
    about: {
      'Birth Date': '1990-11-25',
      'Height': "6'0\"",
      'State You Reside In': 'British Columbia',
      'Willingness to Relocate': 'No',
      'Country of Ethnicity': 'Pakistan',
      'Secondary Country of Ethnicity': '',
      'Past Marital Status': 'I was married in the past but have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I always plan to work full-time',
      'Prayer Habits': 'I pray 5 times a day',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic events/classes and listen to lectures sometimes',
      'Halal Food Preference': 'I require a Halal label or need to be told it is Halal',
      'Islamic Affiliation': 'Hanafi',
      'Hijab Status': 'N/A',
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'We both equally share housework and financial responsibilities, Husband provides all finances and Wife will take care of home',
      'Hobbies / Interests': 'Investing, Cycling, Coffee',
    },
    looking: {
      "How Many Years Younger": '5',
      "How Many Years Older": '5',
      "Partner's Height Range (Shortest)": "5'4\"",
      "Partner's Height Range (Tallest)": "5'10\"",
      "Partner's State": 'British Columbia',
      'Country of Ethnicity Preference': 'I am okay with her being any country of ethnicity but prefer my own',
      "Partner's Past Marital Status": 'She was never married and has no kids, She was married in the past but has no kids',
      "Partner's Employment Status": 'Working full-time',
      "Partner's Post-Marriage Employment": 'She always plans to work full-time',
      "Partner's Prayer Habits": 'He prays 5 times a day',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'She requires a Halal label or needs to be told it is Halal',
      "Partner's Islamic Affiliation": 'Hanafi',
      "Partner's Hijab Status": 'She wears a hijab',
      "Partner's Hobbies / Interests": 'Cycling, Coffee',
    },
  },
  {
    id: 'w1',
    full_name: 'Aisha Malik',
    email: 'aisha.malik@example.com',
    gender: 'female',
    age: 26,
    location: 'Toronto, ON',
    occupation: 'UX Designer',
    adminNote: 'Creative professional, loves books and the outdoors.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpAishaMalikBioData/viewform',
    about: {
      'Birth Date': '1999-07-12',
      'Height': "5'5\"",
      'State You Reside In': 'Ontario',
      'Willingness to Relocate': 'Yes',
      'Country of Ethnicity': 'Pakistan',
      'Secondary Country of Ethnicity': '',
      'Past Marital Status': 'I was never married and have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I always plan to work full-time',
      'Prayer Habits': 'I pray 5 times a day',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic events/classes and listen to lectures sometimes',
      'Halal Food Preference': 'I require a Halal label or need to be told it is Halal',
      'Islamic Affiliation': 'Hanafi',
      'Hijab Status': 'I wear a hijab',
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'We both equally share housework and financial responsibilities',
      'Hobbies / Interests': 'Reading, Illustration, Yoga',
    },
    looking: {
      "How Many Years Younger": '3',
      "How Many Years Older": '7',
      "Partner's Height Range (Shortest)": "5'8\"",
      "Partner's Height Range (Tallest)": "6'2\"",
      "Partner's State": 'Ontario',
      'Country of Ethnicity Preference': 'I am okay with him being any country of ethnicity but prefer my own',
      "Partner's Past Marital Status": 'He was never married and has no kids',
      "Partner's Employment Status": 'Working full-time',
      "Partner's Post-Marriage Employment": 'He always plans to work full-time',
      "Partner's Prayer Habits": 'He prays 5 times a day',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'He requires a Halal label or needs to be told it is Halal',
      "Partner's Islamic Affiliation": 'Hanafi',
      "Partner's Hijab Status": 'N/A',
      "Partner's Hobbies / Interests": 'Reading, Hiking',
    },
  },
  {
    id: 'w2',
    full_name: 'Fatima Noor',
    email: 'fatima.noor@example.com',
    gender: 'female',
    age: 29,
    location: 'Mississauga, ON',
    occupation: 'Registered Nurse',
    adminNote: 'Healthcare schedule, prefer someone understanding of shift work.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpFatimaNoorBioData/viewform',
    about: {
      'Birth Date': '1996-12-03',
      'Height': "5'4\"",
      'State You Reside In': 'Ontario',
      'Willingness to Relocate': 'No',
      'Country of Ethnicity': 'Bangladesh',
      'Secondary Country of Ethnicity': '',
      'Past Marital Status': 'I was never married and have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I always plan to work full-time',
      'Prayer Habits': 'I pray 5 times a day',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic events/classes and listen to lectures sometimes',
      'Halal Food Preference': 'I require a Halal label or need to be told it is Halal',
      'Islamic Affiliation': 'Hanafi',
      'Hijab Status': 'I wear a hijab',
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'We both equally share housework and financial responsibilities',
      'Hobbies / Interests': 'Travel, Volunteering, Calligraphy',
    },
    looking: {
      "How Many Years Younger": '3',
      "How Many Years Older": '7',
      "Partner's Height Range (Shortest)": "5'8\"",
      "Partner's Height Range (Tallest)": "6'1\"",
      "Partner's State": 'Ontario',
      'Country of Ethnicity Preference': 'He must be from my country of ethnicity',
      "Partner's Past Marital Status": 'He was never married and has no kids',
      "Partner's Employment Status": 'Working full-time',
      "Partner's Post-Marriage Employment": 'He always plans to work full-time',
      "Partner's Prayer Habits": 'He prays 5 times a day',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'He requires a Halal label or needs to be told it is Halal',
      "Partner's Islamic Affiliation": 'Hanafi',
      "Partner's Hijab Status": 'N/A',
      "Partner's Hobbies / Interests": 'Travel, Volunteering',
    },
  },
  {
    id: 'w3',
    full_name: 'Zainab Hussain',
    email: 'zainab.hussain@example.com',
    gender: 'female',
    age: 31,
    location: 'Calgary, AB',
    occupation: 'Marketing Manager',
    adminNote: 'Willing to relocate for the right person.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpZainabHussainBioData/viewform',
    about: {
      'Birth Date': '1994-09-18',
      'Height': "5'6\"",
      'State You Reside In': 'Alberta',
      'Willingness to Relocate': 'Yes',
      'Country of Ethnicity': 'Egypt',
      'Secondary Country of Ethnicity': '',
      'Past Marital Status': 'I was never married and have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I plan to work full-time and then part-time after kids',
      'Prayer Habits': 'I am trying my best to pray 5 times daily but occasionally miss',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic classes a once or few times a week',
      'Halal Food Preference': 'I need to at least be told that the meat is hand-slaughtered',
      'Islamic Affiliation': 'Shafi',
      'Hijab Status': "I don't wear a hijab but am working towards it",
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'We both equally share housework and financial responsibilities',
      'Hobbies / Interests': 'Photography, Cooking, Hiking',
    },
    looking: {
      "How Many Years Younger": '3',
      "How Many Years Older": '5',
      "Partner's Height Range (Shortest)": "5'7\"",
      "Partner's Height Range (Tallest)": "6'0\"",
      "Partner's State": 'Alberta',
      'Country of Ethnicity Preference': 'I am okay with any country of ethnicity',
      "Partner's Past Marital Status": 'He was never married and has no kids',
      "Partner's Employment Status": 'Working full-time',
      "Partner's Post-Marriage Employment": 'He always plans to work full-time',
      "Partner's Prayer Habits": 'He prays 5 times a day, He is trying his best to pray 5 times daily but occasionally misses',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic classes a once or few times a week, He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'He needs to at least be told that the meat is hand-slaughtered',
      "Partner's Islamic Affiliation": 'Shafi, Hanafi',
      "Partner's Hijab Status": 'N/A',
      "Partner's Hobbies / Interests": 'Soccer, Photography, Cooking',
    },
  },
  {
    id: 'w4',
    full_name: 'Maryam Iqbal',
    email: 'maryam.iqbal@example.com',
    gender: 'female',
    age: 33,
    location: 'Vancouver, BC',
    occupation: 'Dentist',
    adminNote: 'Established career in Vancouver, prefer to stay locally.',
    bioDataUrl: 'https://docs.google.com/forms/d/e/2AIbpMaryamIqbalBioData/viewform',
    about: {
      'Birth Date': '1992-04-22',
      'Height': "5'7\"",
      'State You Reside In': 'British Columbia',
      'Willingness to Relocate': 'No',
      'Country of Ethnicity': 'Pakistan',
      'Secondary Country of Ethnicity': 'India',
      'Past Marital Status': 'I was never married and have no kids',
      'Employment Status': 'Working full time',
      'Post-Marriage Employment': 'I always plan to work full-time',
      'Prayer Habits': 'I pray 5 times a day',
      'Involvement In An Islamic Atmosphere': 'I attend Islamic events/classes and listen to lectures sometimes',
      'Halal Food Preference': 'I require a Halal label or need to be told it is Halal',
      'Islamic Affiliation': 'Hanafi',
      'Hijab Status': 'I wear a hijab',
      'Living Situation Post Marriage': 'Live separately from parents',
      'Financial and Home Roles': 'We both equally share housework and financial responsibilities, Husband provides all finances and Wife will take care of home',
      'Hobbies / Interests': 'Cycling, Coffee, Painting',
    },
    looking: {
      "How Many Years Younger": '3',
      "How Many Years Older": '8',
      "Partner's Height Range (Shortest)": "5'9\"",
      "Partner's Height Range (Tallest)": "6'2\"",
      "Partner's State": 'British Columbia',
      'Country of Ethnicity Preference': 'I am okay with him being any country of ethnicity but prefer my own',
      "Partner's Past Marital Status": 'He was never married and has no kids, He was married in the past but has no kids',
      "Partner's Employment Status": 'Working full-time',
      "Partner's Post-Marriage Employment": 'He always plans to work full-time',
      "Partner's Prayer Habits": 'He prays 5 times a day',
      "Partner's Involvement In An Islamic Atmosphere": 'He attends Islamic events/classes and listens to lectures sometimes',
      "Partner's Halal Food Preference": 'He requires a Halal label or needs to be told it is Halal',
      "Partner's Islamic Affiliation": 'Hanafi',
      "Partner's Hijab Status": 'N/A',
      "Partner's Hobbies / Interests": 'Cycling, Coffee',
    },
  },
];

export const MOCK_PEOPLE: Person[] = peopleRaw.map(buildPerson);
export const MOCK_SHEET_PROFILES: SheetProfile[] = peopleRaw.map(buildSheetProfile);

const iso = (s: string) => new Date(s).toISOString();

export const MOCK_MATCHES: Match[] = [
  {
    id: 'match-1',
    person_1_id: 'm1',
    person_2_id: 'w1',
    paired_at: iso('2025-02-01T12:00:00Z'),
    exchanged_contact: true,
    outcome: 'pending',
    outcome_set_at: null,
    notes: 'High compatibility on location, education, prayer, hobbies.',
  },
  {
    id: 'match-2',
    person_1_id: 'm2',
    person_2_id: 'w2',
    paired_at: iso('2025-01-15T12:00:00Z'),
    exchanged_contact: true,
    outcome: 'worked_out',
    outcome_set_at: iso('2025-03-10T12:00:00Z'),
    notes: 'Both families agreed to proceed; wedding planned.',
  },
  {
    id: 'match-3',
    person_1_id: 'm3',
    person_2_id: 'w3',
    paired_at: iso('2025-01-20T12:00:00Z'),
    exchanged_contact: false,
    outcome: 'failed',
    outcome_set_at: iso('2025-02-18T12:00:00Z'),
    notes: 'Different long-term city plans; incompatible.',
  },
  {
    id: 'match-4',
    person_1_id: 'm4',
    person_2_id: 'w4',
    paired_at: iso('2025-02-10T12:00:00Z'),
    exchanged_contact: true,
    outcome: 'manually_removed',
    outcome_set_at: iso('2025-02-25T12:00:00Z'),
    notes: 'Candidate paused the process; revisit later.',
  },
];
